#!/bin/bash
set -e

export PATH="$HOME/.foundry/bin:$HOME/.drosera/bin:$PATH"

WALLET_ADDRESS="0xc93bf33438c9c636fc49cafe1086c2c424507a15"
DROSERA_CALLER="${DROSERA_CALLER:-$WALLET_ADDRESS}"
HOODI_RPC="${RPC_URL:-https://ethereum-hoodi-rpc.publicnode.com}"
COOLDOWN_BLOCKS="${COOLDOWN_BLOCKS:-33}"
MOCK_ADDRESS="${MOCK_ADDRESS:-}"

if [ -z "$PRIVATE_KEY" ]; then
    echo "ERROR: PRIVATE_KEY not set"; exit 1
fi
if [ -z "$MOCK_ADDRESS" ]; then
    echo "ERROR: MOCK_ADDRESS not set (export MOCK_ADDRESS=0x...)"; exit 1
fi

cd /mnt/c/Users/ndohj/2026/drosera-beanstalk-trap

echo ""
echo "================================================="
echo "  Beanstalk Governance Trap - Resume Deployment"
echo "================================================="
echo "  Using existing BeanstalkMock: $MOCK_ADDRESS"
echo ""

# Step 1b: Generate static trap deploy config with the existing mock address
echo ">>> Step 1b: Generating TrapDeployConfig.sol..."
cat > src/TrapDeployConfig.sol <<EOF
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

library TrapDeployConfig {
    // Generated by resume-deploy.sh
    address internal constant TARGET = ${MOCK_ADDRESS};
}
EOF
echo "TrapDeployConfig.sol generated."
echo ""

# Step 1c: Rebuild with the generated config
echo ">>> Step 1c: Building contracts..."
forge build 2>&1
echo ""

# Step 2: Deploy BeanstalkAttacker
echo ">>> Step 2: Deploying BeanstalkAttacker..."
ATTACKER_OUTPUT=$(forge create src/BeanstalkAttacker.sol:BeanstalkAttacker \
    --rpc-url "$HOODI_RPC" \
    --private-key "$PRIVATE_KEY" \
    --broadcast \
    --constructor-args "$MOCK_ADDRESS" 2>&1) || { echo "STEP 2 FAILED"; echo "$ATTACKER_OUTPUT"; exit 1; }
echo "$ATTACKER_OUTPUT"
ATTACKER_ADDRESS=$(echo "$ATTACKER_OUTPUT" | grep -oP "Deployed to: \K0x[a-fA-F0-9]{40}")
if [ -z "$ATTACKER_ADDRESS" ]; then echo "ERROR: Could not parse BeanstalkAttacker address"; exit 1; fi
echo "BeanstalkAttacker: $ATTACKER_ADDRESS"
echo ""

# Step 3: Deploy BeanstalkVaultV2
echo ">>> Step 3: Deploying BeanstalkVaultV2..."
VAULT_OUTPUT=$(forge create src/BeanstalkVaultV2.sol:BeanstalkVaultV2 \
    --rpc-url "$HOODI_RPC" \
    --private-key "$PRIVATE_KEY" \
    --broadcast \
    --constructor-args "$MOCK_ADDRESS" "$DROSERA_CALLER" "$COOLDOWN_BLOCKS" 2>&1) || { echo "STEP 3 FAILED"; echo "$VAULT_OUTPUT"; exit 1; }
echo "$VAULT_OUTPUT"
VAULT_ADDRESS=$(echo "$VAULT_OUTPUT" | grep -oP "Deployed to: \K0x[a-fA-F0-9]{40}")
if [ -z "$VAULT_ADDRESS" ]; then echo "ERROR: Could not parse BeanstalkVaultV2 address"; exit 1; fi
echo "BeanstalkVaultV2: $VAULT_ADDRESS"
echo ""

# Step 3b: Wire pause guardian to BeanstalkVaultV2
echo ">>> Step 3b: Setting pause guardian to BeanstalkVaultV2..."
SET_GUARDIAN_OUTPUT=$(cast send "$MOCK_ADDRESS" \
    "setPauseGuardian(address)" "$VAULT_ADDRESS" \
    --rpc-url "$HOODI_RPC" \
    --private-key "$PRIVATE_KEY" 2>&1) || { echo "STEP 3b FAILED"; echo "$SET_GUARDIAN_OUTPUT"; exit 1; }
echo "$SET_GUARDIAN_OUTPUT"
echo "Pause guardian set to vault."
echo ""

# Step 4: Deploy BeanstalkTrapV2 (no configure() call — target is baked in via TrapDeployConfig)
echo ">>> Step 4: Deploying BeanstalkTrapV2..."
TRAP_OUTPUT=$(forge create src/BeanstalkTrapV2.sol:BeanstalkTrapV2 \
    --rpc-url "$HOODI_RPC" \
    --private-key "$PRIVATE_KEY" \
    --broadcast 2>&1) || { echo "STEP 4 FAILED"; echo "$TRAP_OUTPUT"; exit 1; }
echo "$TRAP_OUTPUT"
TRAP_ADDRESS=$(echo "$TRAP_OUTPUT" | grep -oP "Deployed to: \K0x[a-fA-F0-9]{40}")
if [ -z "$TRAP_ADDRESS" ]; then echo "ERROR: Could not parse BeanstalkTrapV2 address"; exit 1; fi
echo "BeanstalkTrapV2: $TRAP_ADDRESS"
echo ""

# Step 5: Write drosera.toml
echo ">>> Step 5: Writing drosera.toml..."
cat > drosera.toml <<EOF
ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps.beanstalk_governance_trap]
path = "out/BeanstalkTrapV2.sol/BeanstalkTrapV2.json"
address = "${TRAP_ADDRESS}"
response_contract = "${VAULT_ADDRESS}"
response_function = "executeResponse(bytes)"
cooldown_period_blocks = ${COOLDOWN_BLOCKS}
block_sample_size = 2
min_number_of_operators = 3
max_number_of_operators = 7
private_trap = false
whitelist = []
EOF
echo "drosera.toml written."
echo ""

echo "================================================="
echo "  ALL CONTRACTS DEPLOYED ON HOODI"
echo "================================================="
echo "  BeanstalkMock:     $MOCK_ADDRESS"
echo "  BeanstalkAttacker: $ATTACKER_ADDRESS"
echo "  BeanstalkVaultV2:  $VAULT_ADDRESS"
echo "  BeanstalkTrapV2:   $TRAP_ADDRESS"
echo "================================================="
echo ""
echo "NEXT: register the Trap with Drosera:"
echo "  drosera apply"
echo ""
